work_dir: ./work_dir/NTU-RGB-D/xview/ST_GCN_relation_complete2graph_senet_mask_resume40

# feeder
feeder: st_gcn_relation.feeder.Feeder
train_feeder_args:
  mode: train
  window_size: 300
  data_path: ../data/NTU-RGB-D/xview/train_data.npy
  label_path: ../data/NTU-RGB-D/xview/train_label.pkl
test_feeder_args:
  mode: test
  window_size: 300
  data_path: ../data/NTU-RGB-D/xview/val_data.npy
  label_path: ../data/NTU-RGB-D/xview/val_label.pkl

# model
model: st_gcn_relation.net.ST_GCN_RELATION
model_args:
  num_class: 60
  channel: 28
  window_size: 300
  num_point: 25
  num_person: 2
  graph: st_gcn_relation.graph.NTU_RGB_D
  graph_args:
    labeling_mode: 'completerelation2graph'
  mask_learning: True
  use_data_bn: True

#optim
use_L1: False
L1_weight_decay: 0.0001
weight_decay: 0.0001
base_lr: 0.1
step: [10, 40]

# training
device: [0,1,2,3]
batch_size: 64
test_batch_size: 64
num_epoch: 80
nesterov: True